store-rest-api/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('product/payment/<int:pk>', views.make_pay_paypal, name='payment'),
    path('product/payment/success/<int:pk>',
         views.payment_success, name='success'),
    path('product/payment/cancelled', views.payment_cancelled, name='cancelled'),
    path('product/payed/detail/<int:pk>', views.detail_pay, name='detail_pay'),

    path('purchased', views.purchased, name='purchased'),
    path('product/<int:pk>', views.DetailView.as_view(), name='detail'),
    path('product/<slug:url_clean>', views.DetailView.as_view(), name='detail'),
]

store-rest-api/store/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(('products.urls', 'products'), namespace='products')),
    path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

store-rest-api/shop/models.py
from django.db import models
from django.contrib.auth.models import User

from products.models import Product


class Payment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    payment_id = models.CharField(max_length=200)
    payer_id = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    @classmethod
    def create(cls, payment_id, payer_id, price, user_id, product_id):

        payment = cls(
            payment_id=payment_id,
            payer_id=payer_id,
            price=price,
            user=user_id,
            product=product_id
        )

        return payment

    def __str__(self) -> str:
        return self.price

store-rest-api/shop/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, reverse, render
from django.core.paginator import Paginator
from django.views import generic
from paypalcheckoutsdk.core import PayPalHttpClient, SandboxEnvironment
from paypalcheckoutsdk.orders import OrdersCreateRequest, OrdersCaptureRequest
from paypalhttp import HttpError
import environ

from products.models import Category, Product
from shop.models import Payment

env = environ.Env()


def index(req):
    categories = Category.objects.all()

    search = req.GET.get('search')
    category = req.GET.get('category')

    if search:
        products = Product.objects.filter(type=1, title__contains=search)
    else:
        products = Product.objects.filter(type=1)
        search = ''

    if category:
        products = products .filter(category_id=category)
        category = int(category)
    else:
        category = ''

    paginator = Paginator(products, 5)
    page_number = req.GET.get('page')
    products_page = paginator.get_page(page_number)

    return render(req, 'store/index.html', {
        'products': products_page,
        'categories': categories,
        'search': search,
        'category': category
    })


class DetailView(generic.DetailView):
    model = Product
    template_name = 'store/detail.html'
    slug_field = 'url_clean'
    slug_url_kwarg = 'url_clean'


@login_required
def make_pay_paypal(req, pk):
    product = get_object_or_404(Product, pk=pk)

    client_id = env("PAYPAL_CLIENT_ID")
    client_secret = env("PAYPAL_CLIENT_SECRET")
    environment = SandboxEnvironment(
        client_id=client_id, client_secret=client_secret)
    client = PayPalHttpClient(environment)

    order_request = OrdersCreateRequest()
    order_request.prefer('return=representation')
    order_request.request_body({
        "intent": "CAPTURE",
        "purchase_units": [
            {
                "amount": {
                    "currency_code": "USD",
                    "value": "100.00"
                }
            }
        ],
        "application_context": {
            "return_url": "http://localhost:8000/shop/product/payment/success/%s" % product.id,
            "cancel_url": "http://localhost:8000/shop/product/payment/cancelled"
        }
    })

    try:
        response = client.execute(order_request)

        if response.result.status == "CREATED":
            approval_url = str(response.result.links[1].href)
    except IOError as ioe:
        print(ioe)
        if isinstance(ioe, HttpError):
            print(ioe.status_code)

    return render(req, 'payment/buy.html', {'product': product, 'approval_url': approval_url})


@login_required
def payment_success(req, pk):
    product = get_object_or_404(Product, pk=pk)

    client_id = env("PAYPAL_CLIENT_ID")
    client_secret = env("PAYPAL_CLIENT_SECRET")
    environment = SandboxEnvironment(
        client_id=client_id, client_secret=client_secret)
    client = PayPalHttpClient(environment)

    order_id = req.GET.get('token')
    payer_id = req.GET.get('PayerID')

    request = OrdersCaptureRequest(order_id)

    try:
        response = client.execute(request)

        if response:
            paymentModel = Payment.create(
                payment_id=order_id,
                payer_id=payer_id,
                price=product.price,
                user_id=req.user,
                product_id=product,
            )

            paymentModel.save()

            return redirect(reverse('shop:detail_pay', args=[paymentModel.id]))

    except IOError as ioe:
        if isinstance(ioe, HttpError):
            print(ioe.status_code)

    return render(req, 'payment/success.html')


@login_required
def payment_cancelled(req):
    return render(req, 'payment/cancelled.html')


@login_required
def purchased(req):
    return render(req, 'payment/purchased.html', {'payments': Payment.objects.select_related('product').filter(user=req.user)})


@login_required
def detail_pay(req, pk):
    payment = get_object_or_404(Payment, pk=pk)
    return render(req, 'payment/detail.html', {'payment': payment})

store-rest-api/shop/templates/store/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Shop{% endblock %}</title>
  {% load static %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/shop-style.css' %}">
</head>
<body>
  {% block main %}{% endblock %}
</body>
</html>

store-rest-api/shop/templates/store/detail.html
{% extends "store/base.html" %}

{% block main %}
  <div class="p-3 mb-2 bg-primary text-white text-center">
    <h1 class="display-1">{{product.title}}</h1>
  </div>
{% endblock %}

store-rest-api/shop/templates/store/index.html
{% extends "store/base.html" %}

{% block main %}
  <div class="hero mb-5">
    <div class="container">
      <form class="form">
        <div class="input-group">
          <input type="text" name="search" value="{{ search }}" class="form-control mr-2">
          <select name="category" class="form-control">
            {% for c in categories %}
              <option 
                {% if category_id == c.id %} selected {% endif %} 
                value="{{c.id}}">
                  {{c.title}}
              </option>
            {% endfor %}
          </select>
          <button type="submit" class="btn btn-warning">Search</button>
        </div>
      </form>
    </div>
  </div>

  <div class="container">
    <table class="table table-striped">
      <tbody>
        {% for p in products %}
          <tr class="table-row">
            <td>{{ p.title }}</td>
            <td>{{ p.description }}</td>
            <td>{{ p.price }}</td>
            <td class="actions">
              {% comment %} <a class="btn btn-small" href="{% url 'shop:detail' p.id %}">Go</a> {% endcomment %}
              <a class="btn btn-primary btn-sm" href="{% url 'shop:detail' p.url_clean %}">View</a>
              <a class="btn btn-success btn-sm" href="{% url 'shop:payment' p.id %}">Buy</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}