store-rest-api/comments/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('update/<int:pk>', views.update, name='update'),
    path('contact/', views.contact, name='contact'),
    path('export/', views.export, name='export')
]

store-rest-api/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('product/payment/<int:pk>', views.make_pay_paypal, name='payment'),
    path('product/payment/success/<int:pk>',
         views.payment_success, name='success'),
    path('product/payment/cancelled', views.payment_cancelled, name='cancelled'),
    path('product/payed/detail/<int:pk>', views.detail_pay, name='detail_pay'),

    path('purchased', views.purchased, name='purchased'),
    path('product/<int:pk>', views.DetailView.as_view(), name='detail'),
    path('product/<slug:url_clean>', views.DetailView.as_view(), name='detail'),
]

store-rest-api/store/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(('products.urls', 'products'), namespace='products')),
    path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

store-rest-api/comments/models.py
from django.db import models

from products.models import Product


class Comment(models.Model):
    text = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(
        Product,
        related_name='comments',
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self) -> str:
        return 'Comment #{}'.format(self.id)


class Contact(models.Model):
    name = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    email = models.CharField(max_length=70)
    phone = models.CharField(max_length=15)
    date = models.DateField()
    document = models.FileField(upload_to='uploads/contact')


class TypeContact(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name

store-rest-api/comments/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from django.core.validators import EmailValidator, MinLengthValidator
from django.forms.utils import ErrorList

from comments.models import Comment, TypeContact


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': Textarea(attrs={'class': 'form-input'})
        }


class ContactForm(forms.Form):
    CHOICES = (
        (1, 'Bussiness'),
        (2, 'Personal'),
        (3, 'Other'),
    )

    name = forms.CharField(validators=[
        MinLengthValidator(2, message='Name Error %(limit_value)d')
    ])
    lastname = forms.CharField(required=False, max_length=15, min_length=3)
    phone = forms.RegexField(
        regex='\(\w{3}\)\w{3}-\w{4}',
        max_length=13,
        min_length=13
    )
    email = forms.EmailField(validators=[EmailValidator()])
    birth_date = forms.DateField()
    # contact = forms.ChoiceField(queryset=TypeContact.objects.all())
    document = forms.FileField(required=False)
    terms = forms.BooleanField()


class DivErrorList(ErrorList):
    def __str__(self):
        return ''

    def as_divs(self):
        if not self:
            return ''
        return ''

store-rest-api/comments/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.core.mail import send_mail
from django.template import loader
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.utils.translation import gettext as _
import csv

from comments.models import Comment, Contact
from comments.forms import CommentForm, ContactForm, DivErrorList


def index(req):
    comments = Comment.objects.all()
    p = Paginator(comments, 5)

    page_number = req.GET.get('page')
    comments_page = p.get_page(page_number)

    return render(req, 'index_page.html', {'comments_page': comments_page})


def add(req):
    if req.method == 'POST':
        form = CommentForm(req.POST)

        if form.is_valid():
            comment = form.save()

            html_message = loader.render_to_string(
                'email/comment.html',
                {'comment', comment}
            )

            req.session['comment_id'] = comment.id

            send_mail(
                "Comment #" + str(comment.id),
                comment.text,
                "davee@gmail.com",
                ["juan@gmail.com"],
                fail_silently=False,
                html_message=html_message
            )

            return redirect('comments:index')
    else:
        form = CommentForm()

    return render(req, 'add.html', {'form': form})


def update(req, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if req.method == 'POST':
        form = CommentForm(req.POST, instance=comment)

        if form.is_valid():
            form.save()
            return redirect('comments:update', pk=pk)
    else:
        form = CommentForm(instance=comment)

    return render(req, 'update.html', {
        'form': form,
        'comment': comment
    })


def contact(req):
    if req.method == 'POST':
        form = ContactForm(req.POST, req.FILES, error_class=DivErrorList)

        if form.is_valid():
            contact = Contact()

            if 'document' in req.FILES['document']:
                contact.document = req.FILES['document']

            contact.name = form.cleaned_data['name']
            contact.lastname = form.cleaned_data['lastname']
            contact.email = form.cleaned_data['email']
            contact.phone = form.cleaned_data['phone']
            contact.dirthdate = form.cleaned_data['dirthdate']

            contact.save()
    else:
        form = ContactForm()

    return render(req, 'contact.html', {'form': form})


def export(req):
    comments = Comment.objects.all()

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="comments.csv"'},
    )

    writer = csv.writer(response)

    for c in comments:
        writer.writerow([c.id, c.text])

    return response

store-rest-api/comments/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Forms Handling - Add</title>
</head>
<body>
  <form action="{% url 'comments:add' %}" method="post">
    {% csrf_token %}
    {{ form.text }}
    <button type="Submit">Save</button>
  </form>
</body>
</html>

store-rest-api/comments/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Contact Form</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>
<body>
  <div class="row">
    <div class="col s6 offset-s3">
      <div class="card-panel center-align teal lighten-2 white-text text-darken-2">
        <span class="flow-text">Contact Form</span> 
      </div>

      <form method="post" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}

        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <div><strong>{{ error }}</strong></div>
            {% endfor %}
          {% endfor %}
        {% endif %}

        {{ form }}

        <div class="right-align">
          <button type="submit" class="waves-effect waves-light btn">Send Form</button>
        </div>
      </form>
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

store-rest-api/comments/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Forms Handling</title>
</head>
<body>
  {% for c in comments %}
    <p>{{ c.text }}</p>
  {% endfor %}
</body>
</html>

store-rest-api/comments/templates/index_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Forms Handling</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
  {% for c in comments_page %}
    <p>{{ c.text }}</p>
  {% endfor %}
  
  {% include 'partials/pagination.html' with page_obj=comments_page %}
</body>
</html>

store-rest-api/comments/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Forms Handling - Update</title>
</head>
<body>
  <form action="{% url 'comments:update' comment.id %}" method="post">
    {% csrf_token %}
    {{ form.text }}
    <button type="Submit">Update</button>
  </form>
</body>
</html>